### ISSUE TITLE
POST to /tradition can throw MultipleFoundException

### ISSUE THREAD

**Issue by oftl** [DHUniWien/tradition_repo#15]
It is possible to create more than one user with the same userId. POSTing to /tradition and referencing that userId will throw org.neo4j.graphdb.MultipleFoundException.

**Comment by tla** [comment]
I'm having trouble reproducing this - any ideas? 

(The only way I can see to create more than one user is to do it manually by mucking around with the DB directly, as sometimes happens in the test suite; there is only one call to `db.createNode(Nodes.USER)` in the code, and that is checked.)
